[options] --msgid-bugs-address jafesp@gmail.com

[options] --copyright-holder "Jamenson Ferreira Espindula de Almeida Melo"

[options] --package-name GNU Bash

[options] --package-version 4.3

[options] --keep 0

[po4a_paths] man/po/pt_BR.pot pt_BR:man/po/pt_BR.po

[type: man] man/bash.1 pt_BR:man/translated/bash.1 opt:"-o groff_code=verbatim" opt:"-o unknown_macros=translate_each" opt:"-o translate_each=}1" opt:"-o translate_each=FN"
